### ISSUE TITLE
should SVG width be updated on resize?

### ISSUE THREAD

**Issue by mbsimonovic** [opencb/genome-maps#22]
SVG width is set initially while rendering the page and then it's not updated on window resize.

As you can see on this screenshot, opening the page on 635px and resizing afterwards leaves the window cut off:
![screen shot 2015-09-16 at 00 05 39](https://cloud.githubusercontent.com/assets/888008/9891464/b8c7ec62-5c06-11e5-818f-3ed9436f47b7.png)

**Comment by frasator** [comment]
True, I have updated it, now should work, thanks!
